apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 3 # Eixo X: 3 instâncias processando o Sharding
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: service-a-users:latest
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: "postgres-db"         # Aponta para o Service Default
        - name: DB_HOST_SHARD2
          value: "postgres-db-shard2"  # Aponta para o Service Premium
        - name: SERVICE_B_URL
          value: "http://service-b:8000"
        - name: SERVICE_C_URL
          value: "http://service-c:8000"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30001
  selector:
    app: service-a