apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
      - name: service-c
        image: service-c-audit:latest
        imagePullPolicy: Never
        env:
        - name: MONGO_URL
          value: "mongodb://admin:password@mongodb:27017"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://jaeger:4318"
---
apiVersion: v1
kind: Service
metadata:
  name: service-c
spec:
  ports:
    - port: 8000
  selector:
    app: service-c